# Generated by Django 3.1.4 on 2021-02-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
